### ISSUE TITLE
Fix: Center the Navbar items; they are currently slightly left-aligned

### ISSUE THREAD

**Issue by bibekshhh** [ZIELN/zieln-frontend#91]
![image](https://github.com/ZIELN/zieln-frontend/assets/90471455/cfa4a1cd-69dd-4449-bcca-51b2dbb40782)

**Comment by bini2002** [comment]
![image](https://github.com/ZIELN/zieln-frontend/assets/140949534/a99c45b0-ae3e-4c94-9f5e-08e029015c86)
![image](https://github.com/ZIELN/zieln-frontend/assets/140949534/3498f967-f42a-4aae-907b-b6d74ab1f02c)

It looks like the nav content isn't centered or slightly left aligned because the "Create Event" button is taking up space on the right side.
